name: Deploy to GitHub Pages

on:
  push:
    branches: ['master']

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: master
      
      - name: Debug git status
        run: |
          echo "Current branch:"
          git branch --show-current
          echo "Latest commit:"
          git log -1 --oneline
          echo "All branches:"
          git branch -a
      
      - name: Clean
        run: |
          cd frontend
          rm -rf dist node_modules package-lock.json
          
      - name: Verify branch and files
        run: |
          git branch --show-current
          git log -1 --pretty=format:"%h %s"
          ls -la frontend/src/components/
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'
      
      - name: Install dependencies
        run: |
          cd frontend
          npm install
      
      - name: Build
        run: |
          cd frontend
          npm run build
          echo "Contents of frontend/dist directory:"
          ls -la dist
          echo "Contents of dist/assets (if it exists):"
          ls -la dist/assets || echo "No assets directory found"
          echo "Contents of dist/index.html (if it exists):"
          cat dist/index.html || echo "No index.html found"
      
      - name: Verify build output
        run: |
          cd frontend
          echo "Checking for main CSS and JS files:"
          find dist -type f -name "*.js" -o -name "*.css"
          echo "Checking index.html content:"
          cat dist/index.html
          echo "Checking asset paths in index.html:"
          grep -o 'src="[^"]*"' dist/index.html
          grep -o 'href="[^"]*"' dist/index.html
      
      - name: Setup Pages
        uses: actions/configure-pages@v5
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './frontend/dist'
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4